import { Inter } from "next/font/google";
import "../globals.css";
import Main from "@/components/Main";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden h-screen bg-[#F1F3F6]`}>
      <ToastContainer />
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
